### ISSUE TITLE
Can I add Japanese to this add-on language?

### ISSUE THREAD

**Issue by Shitennouji** [IsaacSchemm/autoplay-toggle#2]
Thank you for this add-on.
It works as expected.
For me, it is one of my favorite addons.

by the way,
This add-on is not available in Japanese. It is a barrier for Japanese who dislike applications in different languages.
If possible, I will cooperate in translating into Japanese.

**Comment by IsaacSchemm** [comment]
I added a ja-JP directory. Feel free to send a pull request with changes to those files, or just send me the translated text by posting it here.

**Comment by Shitennouji** [comment]
title=Autoplay Toggle（自動再生の「On/Off」切り替え機能）
labelOn=自動再生 (On)
labelOff=自動再生 (Off)
enableOrReinstallRequired=この拡張機能を使用するには、有効にするか再インストールする必要があります。
turnedOn=自動再生が On になっています。\現在のページを更新する必要があるかもしれません。
turnedOff=自動再生が Off になっています。

!ENTITY notifyType.label "自動再生の「On/Off」切り替え機能"

!ENTITY notifyType.label "切り替え時の通知の種類"
!ENTITY notifyType.nonModal.label "標準の通知"
!ENTITY notifyType.alert.label "モーダルダイアログ（Modal dialog）"
!ENTITY notifyType.none.label "通知なし"

-------------------------------------------------------------------------------------------------------------------
Postscript : 
About the items displayed in the add-on manager
Autoplay Toggle (Non-Restartless) = Autoplay Toggle（再起動なし）
Adds a toolbar button to toggle autoplay on and off. = 自動再生のオンとオフを切り替えるツールバーボタンを追加します。

**Comment by Shitennouji** [comment]
I have confirmed the updated version "Autoplay Toggle (Non-Restartless) 1.0.2".
Apply immediately!
Everything is fine. 
Thank you very much.
